## Profiling plot taxonomy


```{r}
library(lineprof)
for (path in list.files("R", full.names = TRUE)) { source(path) }
```


```{r}
# Parse taxonomy and sequnences:
file_path <- "~/repositories/Reports/2015_04_02-metacoder-spring_cgrb_conference_poster/trainset10_082014.rdp.fasta" 
seqs <- ape::read.dna(file_path, format = "fasta")
original <- extract_taxonomy(seqs,
                         regex = "^.*\\t(.*)",
                         key = c("class_name"),
                         class_tax_sep = ";",
                         database = "none")
profile <- lineprof(plot_taxonomy(taxon_id = original$taxon_id, parent_id = original$parent_id,
                                  vertex_size = taxon_data(original, "item_count"),
                                  vertex_color = taxon_data(original, "item_count"),
                                  vertex_label = taxon_data(original, "name")))
shine(profile)
```


```{r}
# Make balanced subsample:
subsampled <- taxonomic_sample(original,
                      max_counts = c("3" = 100,
                                     "4" = 20),
                      min_counts = c("4" = 5)) 
subsampled <- subset(subsampled, item_count > 0, itemless = FALSE) 
plot(subsampled,
     vertex_size = item_count,
     vertex_color = item_count,
     vertex_label = name) 

```

