---
title: "Extracting taxonomy information from sequence metadata"
author: "Zachary Foster"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{Extracting taxonomy information from sequence headers}
%\VignetteEngine{knitr::rmarkdown}
%\usepackage[utf8]{inputenc}
---


```{r}
library(ape)
library(metacoder)
```




### Genbank FASTA headers

```{r}
sequences <- ape::read.FASTA("inst/extdata/ncbi_basidiomycetes.fasta")
tax_info <- extract_taxonomy(names(sequences),
                             regex = "^.*\\|(.*)\\|.*\\|(.*)\\|.*$",
                             key = c("item_id", other_id = "item_info"),
                             database = "ncbi")
```


### UNITE FASTA headers

```{r}
sequences <- ape::read.FASTA("inst/extdata/unite_general_release.fasta")
tax_info <- extract_taxonomy(names(sequences),
                             regex = "^(.*)\\|(.*)\\|(.*)\\|.*\\|(.*)$",
                             key = c("taxon_name", "item_id", sh = "taxon_info", "lineage"),
                             database = "ncbi")
```


### ITS1 DB FASTA headers

```{r}
sequences <- ape::read.FASTA("inst/extdata/ITSoneDB_ITS1_GBandHMM.fasta")
tax_info <- extract_taxonomy(names(sequences),
                             regex = "^(.*)_.*\\|(.*)\\|(.*)\\|(.*)$",
                             key = c("item_id", name = "taxon_info",
                                     "taxon_id", description = "taxon_info"),
                             database = "ncbi")
```


### PR2 FASTA headers

```{r}
sequences <- ape::read.FASTA("inst/extdata/pr2_stramenopiles_gb203.fasta")
tax_info <- extract_taxonomy(names(sequences),
                             regex = "^(.*\\..*)\\..*\\|(.*)$",
                             key = c("item_id", "lineage"),
                             database = "ncbi", 
                             lineage_tax_sep = "|")
```


### RDP FASTA headers

```{r}
sequences <- ape::read.FASTA("inst/extdata/rdp_release11_3_Archaea_unaligned.fa")
tax_info <- extract_taxonomy(names(sequences),
                             regex = "^(.*) (.*);(.*)\\tLineage=(.*)",
                             key = c(id = "item_info", description = "item_info",
                                     other_id = "item_info", "lineage"),
                             database = "ncbi", 
                             lineage_tax_sep = ";",
                             lineage_rank_sep = ";", 
                             lineage_rank_rev)
```