---
title: "Subsetting taxonomic data"
output:
  rmarkdown::html_vignette:
    toc: true
    css: custom.css
    includes:
      before_body: doc_prefix.html
      after_body: doc_suffix.html
vignette: >
  %\VignetteIndexEntry{Subsetting taxonomic data}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(ape)
library(metacoder)
library(knitr)
library(ggplot2)
opts_chunk$set(dev='svg', warning = FALSE, message = FALSE, fig.show='hold')
```




## Pepare data

```{r eval=FALSE}
file_path <- system.file("extdata", "unite_general_release.fasta", package = "metacoder")
sequences <- ape::read.FASTA(file_path)
unite_ex_data_3 <- extract_taxonomy(names(sequences),
                            regex = "^(.*)\\|(.*)\\|(.*)\\|.*\\|(.*)$",
                            key = c(name = "item_info", seq_id = "item_info",
                                    other_id = "item_info", "class_name"),
                            database = "none")
```

```{r}
taxa <- unite_ex_data_3$taxa
plot_taxonomy(taxa$taxon_id, taxa$parent_id,
              vertex_size = taxa$item_count,
              vertex_color = taxa$item_count,
              vertex_label = taxa$name)
```


##

```{r}
data <- classified(taxon_id = unite_ex_data_3$taxa$taxon_id,
                   parent_id = unite_ex_data_3$taxa$parent_id,
                   item_taxon_id = unite_ex_data_3$items$item_id,
                   taxon_data = data.frame(name =  unite_ex_data_3$taxa$name,
                                           item_count = unite_ex_data_3$taxa$item_count))
```

```{r}
plot(data, 
     vertex_size = item_count,
     vertex_color = item_count,
     vertex_label = name)
```



```{r}
plot(subset_classified(data, taxon = data$taxon_data$name == "Ascomycota"),
     vertex_size = item_count,
     vertex_color = item_count,
     vertex_label = name)
```

