---
title: "Comparing 16S databases"
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("settings.R")
```

## Run individual analyses

```{r run_all}
library(rmarkdown)
render(input = "01--silva.Rmd")
render(input = "02--rdp.Rmd")
render(input = "03--greengenes.Rmd")
```


## Load plots 

```{r load}
load(file.path(output_folder, "silva_data.RData"))
load(file.path(output_folder, "rdp_data.RData"))
load(file.path(output_folder, "greengenes_data.RData"))
```


## Combine plots

```{r combine}
combo_plot <- gridExtra::grid.arrange(ncol = 2, nrow = 3,
                                      top = "All data                                                           Not amplified        ",
                                      left = "SILVA                                                      RDP                                                              Greengenes",
                                      silva_plot_all, silva_plot_pcr_fail,
                                      rdp_plot_all, rdp_plot_pcr_fail,
                                      greengenes_plot_all, greengenes_plot_pcr_fail)
ggplot2::ggsave(file.path(output_folder, "figure_2--16s_database_comparison.pdf"), 
                combo_plot, width = 7.5, height = 10)
```

